auth_service:
  client_id: ''
  client_secret: ''
  host: ''
email:
  login: ''
  password: ''
mqttBroker:
  host: localhost
  password: root
  port: '1883'
  user: root
send_message:
  frequency: '3'
