base:
  frequency: '3'
email:
  login: smarthome2244@mail.ru
  password: G6kxkJrkgdQqLLN4SKz0
mqttBroker:
  host: mosquitto
  password: admin
  port: '1883'
  user: admin
weather:
  APPID: ''
  city: ''
zigbee:
  topic: zigbee2mqtt
