[tool.poetry]
name = "smarthome"
version = "0.1.0"
description = ""
authors = ["Avex-Evo-2244 <ghbdtn2266@mail.ru>"]

[tool.poetry.dependencies]
python = "3.8"
fastapi = "^0.70.1"
alembic = "^1.7.5"
ormar = {extras = ["mysql"], version = "^0.10.23"}
uvicorn = {extras = ["standard"], version = "^0.16.0"}
bcrypt = "^3.2.0"
PyJWT = "^2.3.0"
PyYAML = "^6.0"
pathlib = "^1.0.1"
requests = "^2.26.0"
yeelight = "^0.7.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
