version: "3.3"

services:
  sh_db:
    image: mariadb
    restart: always
    volumes:
      - bd_data2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangoSmartHome
      - MYSQL_USER=roothome
      - MYSQL_PASSWORD=root
  redis:
    restart: always
    image: redis:5
    ports:
      - 6379:6379
  mosquitto:
    container_name: mosquitto
    build: ./mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto
  client:
    build: ./client
    restart: always
    volumes:
      - client_voluem7:/client/build
  smart_home:
    build: ./SmartHome
    restart: always
    command: bash -c "python3 /home/smart_home/web/manage.py migrate &&
              python3 /home/smart_home/web/manage.py makemigrations &&
              python3 /home/smart_home/web/manage.py collectstatic --no-input --clear &&
              daphne -b 0.0.0.0 -p 8000 SmartHome.asgi:application"
    environment:
      - SMARTHOME_BD_HOST=sh_db
      - SMARTHOME_BD_PORT=3306
      - SMARTHOME_BD_NAME=djangoSmartHome
      - SMARTHOME_BD_USER=roothome
      - SMARTHOME_BD_PASSWORD=root
      - SMARTHOME_REDIS_HOST=redis
      - SMARTHOME_REDIS_PORT=6379
      - SMARTHOME_SOCKET_HOST=smart_home
      - SMARTHOME_SOCKET_PORT=8000
      - DJANGO_SETTINGS_MODULE=SmartHome.settings
    expose:
      - 8000
    volumes:
      - static_voluem:/home/smart_home/web/staticfile
      - media_voluem:/home/smart_home/web/media
    links:
      - redis
    depends_on:
      - sh_db
      - mosquitto
      - redis
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - smart_home
      - client
    volumes:
      - static_voluem:/home/smart_home/web/staticfile
      - media_voluem:/home/smart_home/web/media
      - client_voluem7:/client/build
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    # image: koenkk/zigbee2mqtt:arm32v6
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
volumes:
  bd_data2:
  media_voluem:
  static_voluem:
  client_voluem7:
