version: "3.3"

services:
  sh_db:
    image: mariadb
    # image: 459below/mariadb-armv7:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - bd_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_WS_HOST: ${HOST}
    volumes:
      - client_voluem:/client/build
  smart_home:
    build: ./SmartHome
    restart: always
    command: bash -c "alembic upgrade head &&
              uvicorn main:app --reload --port=8000 --host='0.0.0.0'"
    environment:
      SMARTHOME_BD_HOST: ${SMARTHOME_BD_HOST}
      SMARTHOME_BD_PORT: ${SMARTHOME_BD_PORT}
      SMARTHOME_BD_NAME: ${MYSQL_DATABASE}
      SMARTHOME_BD_USER: ${MYSQL_USER}
      SMARTHOME_BD_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 8000
    volumes:
      - media_voluem:/home/smart_home/web/media
      - ./SmartHome/castom_moduls:/home/smart_home/web/castom_moduls
      - ./SmartHome/files:/home/smart_home/web/files
    depends_on:
      - sh_db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - smart_home
      - client
    volumes:
      - media_voluem:/home/smart_home/web/media
      - client_voluem:/client/build
  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      args:
        MOSQUITTO_USER: ${MOSQUITTO_USER}
        MOSQUITTO_PASSWD: ${MOSQUITTO_PASSWD}
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    environment:
      MQTT_BROKER_URL: mqtt://mosquitto
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    # image: koenkk/zigbee2mqtt:arm32v6
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
volumes:
  bd_data:
  media_voluem:
  client_voluem:
