version: "3.3"

services:
  sh_db:
    image: mariadb
    # image: 459below/mariadb-armv7:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - bd_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SmartHome
      - MYSQL_USER=roothome
      - MYSQL_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 1338:80
    environment:
      - PMA_ARBITRARY=1
  mosquitto:
    container_name: mosquitto
    build: ./mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto
  client:
    build: ./client
    restart: always
    volumes:
      - client_voluem8:/client/build
  smart_home:
    build: ./SmartHome
    restart: always
    command: bash -c "alembic upgrade head &&
              uvicorn main:app --reload --port=8000 --host='0.0.0.0'"
    environment:
      - SMARTHOME_BD_HOST=sh_db
      - SMARTHOME_BD_PORT=3306
      - SMARTHOME_BD_NAME=SmartHome
      - SMARTHOME_BD_USER=roothome
      - SMARTHOME_BD_PASSWORD=root
    expose:
      - 8000
    volumes:
      - media_voluem:/home/smart_home/web/media
      - ./SmartHome/castom_moduls:/home/smart_home/web/castom_moduls
    depends_on:
      - sh_db
      - mosquitto
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - smart_home
      - client
    volumes:
      - media_voluem:/home/smart_home/web/media
      - client_voluem8:/client/build
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    # image: koenkk/zigbee2mqtt:arm32v6
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
volumes:
  bd_data:
  media_voluem:
  client_voluem8:
