"""init

Revision ID: 49cf0f693203
Revises: 
Create Date: 2025-06-29 20:37:08.417373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cf0f693203'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scriptnodes',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('script', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script'], ['scripts.id'], name='fk_scriptnodes_scripts_id_script'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scriptedges',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('script', sa.String(length=200), nullable=True),
    sa.Column('source_node', sa.String(length=200), nullable=True),
    sa.Column('target_node', sa.String(length=200), nullable=True),
    sa.Column('condition_label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['script'], ['scripts.id'], name='fk_scriptedges_scripts_id_script'),
    sa.ForeignKeyConstraint(['source_node'], ['scriptnodes.id'], name='fk_scriptedges_scriptnodes_id_source_node'),
    sa.ForeignKeyConstraint(['target_node'], ['scriptnodes.id'], name='fk_scriptedges_scriptnodes_id_target_node'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scriptedges')
    op.drop_table('scriptnodes')
    op.drop_table('scripts')
    # ### end Alembic commands ###
