"""dashboard users

Revision ID: 7adf894d1ef6
Revises: a57b40d4aec3
Create Date: 2026-08-16 15:01:40.153377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7adf894d1ef6'
down_revision: Union[str, Sequence[str], None] = 'a57b40d4aec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('dashboard_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userdashboard_dashboard_id'), 'userdashboard', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_userdashboard_user_id'), 'userdashboard', ['user_id'], unique=False)
    op.drop_table('userdashboardlink')
    op.drop_table('dashboards')
    op.drop_table('userdashboards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdashboards',
    sa.Column('user_id', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dashboards',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userdashboardlink',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dashboard', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('userdashboard', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['dashboard'], ['dashboards.id'], name=op.f('fk_userdashboardlink_dashboards_dashboard_id'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userdashboard'], ['userdashboards.user_id'], name=op.f('fk_userdashboardlink_userdashboards_userdashboard_user_id'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_userdashboard_user_id'), table_name='userdashboard')
    op.drop_index(op.f('ix_userdashboard_dashboard_id'), table_name='userdashboard')
    op.drop_table('userdashboard')
    # ### end Alembic commands ###
