from enum import Enum

class TypesDeviceEnum(str, Enum):
	LIGHT = "LIGHT"
	SWITCH = "SWITCH"
	LIGHT_DECO = "LIGHT_DECO"
	CLIMATE = "CLIMATE"
	WINDOW = "WINDOW"
	DOOR = "DOOR"
	WINDOW_ILLUMINANCE = "WINDOW_ILLUMINANCE"
	ILLUMINANCE = "ILLUMINANCE"
	MOTION = "MOTION"