# Generated by Django 3.1.5 on 2021-01-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteStyle', models.NullBooleanField(default=True, verbose_name='automatic style')),
                ('staticBackground', models.NullBooleanField(default=False, verbose_name='static background')),
                ('updateFrequency', models.IntegerField(default=10, verbose_name='time update')),
                ('mqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker address')),
                ('loginMqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker login')),
                ('passwordMqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker password')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200, verbose_name='user name')),
                ('UserSurname', models.CharField(default='', max_length=200, verbose_name='user surname')),
                ('UserPassword', models.CharField(max_length=200, verbose_name='user password')),
                ('UserEmail', models.EmailField(max_length=254, verbose_name='user email')),
                ('UserMobile', models.CharField(max_length=200, verbose_name='user mobile')),
                ('UserLevel', models.IntegerField(default=1, verbose_name='user level')),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('Style', models.CharField(default='light', max_length=200, verbose_name='user name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smartHomeApi.user')),
            ],
        ),
    ]
