# Generated by Django 3.1.5 on 2021-01-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0002_classname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='UsersConfig',
        ),
    ]
