# Generated by Django 3.1.5 on 2021-01-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0003_auto_20210128_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=200, verbose_name='device name')),
                ('DeviceSystemName', models.SlugField(max_length=200, verbose_name='device system name')),
                ('DeviceInformation', models.TextField(default='', verbose_name='device info')),
                ('DeviceType', models.SlugField(default='', max_length=200, verbose_name='device type')),
                ('DeviceTypeConnect', models.SlugField(default='', max_length=200, verbose_name='device connect type')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=200, verbose_name='root name')),
            ],
        ),
        migrations.CreateModel(
            name='ValueListDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(max_length=200, verbose_name='device value list type')),
                ('value', models.SlugField(max_length=200, verbose_name='device value list value')),
                ('date', models.DateTimeField(verbose_name='device value element date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.device')),
            ],
        ),
        migrations.CreateModel(
            name='ValueDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(max_length=200, verbose_name='device value type')),
                ('value', models.SlugField(max_length=200, verbose_name='device value value')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.room'),
        ),
        migrations.CreateModel(
            name='ConfigDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(max_length=200, verbose_name='device config type')),
                ('address', models.SlugField(max_length=200, verbose_name='device config address')),
                ('low', models.SlugField(max_length=200, verbose_name='device config low')),
                ('hide', models.SlugField(max_length=200, verbose_name='device config hide')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.device')),
            ],
        ),
    ]
