# Generated by Django 3.1.5 on 2021-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0004_auto_20210129_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdevice',
            name='icon',
            field=models.SlugField(default='', max_length=200, verbose_name='device icon'),
        ),
        migrations.AlterField(
            model_name='configdevice',
            name='hide',
            field=models.SlugField(default='255', max_length=200, verbose_name='device config hide'),
        ),
        migrations.AlterField(
            model_name='configdevice',
            name='low',
            field=models.SlugField(default='0', max_length=200, verbose_name='device config low'),
        ),
    ]
