# Generated by Django 3.1.5 on 2021-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0005_auto_20210130_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configdevice',
            name='hide',
        ),
        migrations.AddField(
            model_name='configdevice',
            name='high',
            field=models.SlugField(default='255', max_length=200, verbose_name='device config high'),
        ),
    ]
