# Generated by Django 3.1.5 on 2021-01-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0006_auto_20210130_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.room'),
        ),
    ]
