# Generated by Django 3.1.5 on 2021-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0007_auto_20210130_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdevice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
