# Generated by Django 3.1.5 on 2021-01-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0009_auto_20210130_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='mqttBroker',
            field=models.CharField(default='', max_length=200, verbose_name='mqttBroker ip'),
        ),
    ]
