# Generated by Django 3.1.5 on 2021-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0010_auto_20210131_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='mqttBrokerPort',
            field=models.CharField(default='', max_length=200, verbose_name='mqttBroker port'),
        ),
    ]
