# Generated by Django 3.1.5 on 2021-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0011_serverconfig_mqttbrokerport'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdevice',
            name='token',
            field=models.SlugField(default='', max_length=200, verbose_name='device token'),
        ),
    ]
