# Generated by Django 3.1.5 on 2021-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0012_configdevice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelistdevice',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
