# Generated by Django 3.1.5 on 2021-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0013_auto_20210209_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='DeviceControl',
            field=models.TextField(default='', max_length=200, verbose_name='device control'),
        ),
    ]
