# Generated by Django 3.1.5 on 2021-02-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0014_device_devicecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.room'),
        ),
        migrations.CreateModel(
            name='HomeCart',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='cart name')),
                ('type', models.CharField(max_length=20, verbose_name='cart name')),
                ('order', models.IntegerField(default=10, verbose_name='cart order')),
                ('homePage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='CartChildren',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='cart name')),
                ('type', models.CharField(max_length=20, verbose_name='cart name')),
                ('typeAction', models.CharField(max_length=20, verbose_name='cart name')),
                ('order', models.IntegerField(default=10, verbose_name='cart order')),
                ('action', models.CharField(default='get', max_length=20, verbose_name='cart name')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device')),
                ('homeCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.homecart')),
            ],
        ),
    ]
