# Generated by Django 3.1.5 on 2021-02-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0015_auto_20210223_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='information',
            field=models.TextField(default='', verbose_name='page info'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='page name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='action',
            field=models.CharField(default='get', max_length=20, verbose_name='element action'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='name',
            field=models.CharField(max_length=50, verbose_name='element name'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='order',
            field=models.IntegerField(default=10, verbose_name='element order'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='type',
            field=models.CharField(max_length=20, verbose_name='element type'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='typeAction',
            field=models.CharField(max_length=20, verbose_name='element typeAction'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='type',
            field=models.CharField(max_length=20, verbose_name='cart type'),
        ),
    ]
