# Generated by Django 3.1.5 on 2021-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0016_auto_20210223_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecart',
            name='idInPage',
            field=models.IntegerField(default=0, max_length=255, verbose_name='id in page'),
            preserve_default=False,
        ),
    ]
