# Generated by Django 3.1.5 on 2021-02-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0017_homecart_idinpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartchildren',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.device'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='order',
            field=models.IntegerField(default=0, verbose_name='element order'),
        ),
    ]
