# Generated by Django 3.1.5 on 2021-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0018_auto_20210225_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartchildren',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='idInPage',
            field=models.IntegerField(verbose_name='id in page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='auteStyle',
            field=models.BooleanField(default=True, verbose_name='automatic style'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='staticBackground',
            field=models.BooleanField(default=False, verbose_name='static background'),
        ),
    ]
