# Generated by Django 3.1.5 on 2021-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0019_auto_20210318_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelistdevice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
