# Generated by Django 3.1.5 on 2021-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0020_auto_20210318_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='название')),
                ('weather', models.CharField(default='base', max_length=200, verbose_name='погода')),
                ('time', models.CharField(default='base', max_length=200, verbose_name='время')),
                ('season', models.CharField(default='summer', max_length=200, verbose_name='время года')),
                ('image', models.ImageField(upload_to='background', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='serverconfig',
            name='auteStyle',
        ),
        migrations.RemoveField(
            model_name='serverconfig',
            name='staticBackground',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='auteStyle',
            field=models.BooleanField(default=True, verbose_name='automatic style'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='staticBackground',
            field=models.BooleanField(default=False, verbose_name='static background'),
        ),
    ]
