# Generated by Django 3.1.5 on 2021-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0021_auto_20210320_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagebackground',
            name='season',
        ),
        migrations.RemoveField(
            model_name='imagebackground',
            name='time',
        ),
        migrations.RemoveField(
            model_name='imagebackground',
            name='weather',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='background',
            field=models.ManyToManyField(related_name='background', to='smartHomeApi.ImageBackground', verbose_name='фон'),
        ),
        migrations.AlterField(
            model_name='imagebackground',
            name='title',
            field=models.CharField(default='base', max_length=200, verbose_name='название'),
        ),
    ]
