# Generated by Django 3.1.5 on 2021-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0022_auto_20210320_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebackground',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
