# Generated by Django 3.1.5 on 2021-03-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0023_auto_20210320_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='user name')),
                ('iconClass', models.CharField(default='fab fa-chrome', max_length=200, verbose_name='user name')),
                ('url', models.SlugField(default='#', max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.user')),
            ],
        ),
    ]
