# Generated by Django 3.1.5 on 2021-03-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0024_menuelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='script name')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
            ],
        ),
        migrations.AlterField(
            model_name='menuelement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, verbose_name='type value device')),
                ('value', models.CharField(default='', max_length=50, verbose_name='type value device')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device')),
            ],
        ),
        migrations.CreateModel(
            name='Triger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type value device')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts')),
            ],
        ),
        migrations.CreateModel(
            name='IfBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type block')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifblock')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts')),
            ],
        ),
        migrations.CreateModel(
            name='If',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type value device')),
                ('ifType', models.CharField(max_length=50, verbose_name='type if')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifblock')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.value')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, verbose_name='type math operation')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.value')),
            ],
        ),
    ]
