# Generated by Django 3.1.5 on 2021-03-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0025_auto_20210323_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='status',
            field=models.BooleanField(default=False, verbose_name='математ'),
        ),
        migrations.AddField(
            model_name='value',
            name='valuefirst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='smartHomeApi.value'),
        ),
        migrations.AddField(
            model_name='value',
            name='valuesecond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='smartHomeApi.value'),
        ),
    ]
