# Generated by Django 3.1.5 on 2021-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0026_auto_20210323_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='triger',
            name='typeDevice',
            field=models.CharField(default='', max_length=50, verbose_name='type value device'),
        ),
        migrations.AlterField(
            model_name='triger',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='type value device'),
        ),
    ]
