# Generated by Django 3.1.5 on 2021-03-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0027_auto_20210326_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triger',
            old_name='typeDevice',
            new_name='action',
        ),
    ]
