# Generated by Django 3.1.5 on 2021-03-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0028_auto_20210328_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfGroupBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type block')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifgroupblock')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts')),
            ],
        ),
        migrations.RemoveField(
            model_name='ifblock',
            name='script',
        ),
        migrations.AddField(
            model_name='ifblock',
            name='action',
            field=models.CharField(default='', max_length=50, verbose_name='type value device'),
        ),
        migrations.AddField(
            model_name='ifblock',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.device'),
        ),
        migrations.AddField(
            model_name='ifblock',
            name='oper',
            field=models.CharField(default='==', max_length=50, verbose_name='operation'),
        ),
        migrations.AddField(
            model_name='ifblock',
            name='value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.value'),
        ),
        migrations.AlterField(
            model_name='ifblock',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type if'),
        ),
        migrations.DeleteModel(
            name='If',
        ),
        migrations.AlterField(
            model_name='ifblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifgroupblock'),
        ),
    ]
