# Generated by Django 3.1.5 on 2021-03-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0029_auto_20210328_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifgroupblock',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts'),
        ),
    ]
