# Generated by Django 3.1.5 on 2021-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0030_auto_20210328_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='status',
        ),
        migrations.AddField(
            model_name='value',
            name='oper',
            field=models.CharField(default='', max_length=50, verbose_name='operation'),
        ),
    ]
