# Generated by Django 3.1.5 on 2021-03-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0031_auto_20210328_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.CharField(default='', max_length=50, verbose_name='action'),
        ),
        migrations.AddField(
            model_name='action',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(default='then', max_length=50, verbose_name='then or else'),
        ),
    ]
