# Generated by Django 3.1.5 on 2021-03-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0032_auto_20210328_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.value'),
        ),
    ]
