# Generated by Django 3.1.5 on 2021-03-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0034_auto_20210328_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifgroupblock',
            name='block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifgroupblock'),
        ),
        migrations.AlterField(
            model_name='ifgroupblock',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.scripts'),
        ),
    ]
