# Generated by Django 3.1.5 on 2021-03-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0035_auto_20210328_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifgroupblock',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartHomeApi.ifgroupblock'),
        ),
    ]
