# Generated by Django 3.1.5 on 2021-03-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0038_auto_20210328_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='background',
        ),
        migrations.DeleteModel(
            name='ImageBackground',
        ),
    ]
