# Generated by Django 3.1.5 on 2021-03-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0039_auto_20210331_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='название')),
                ('image', models.ImageField(upload_to='background', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBackground',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(default='base', max_length=200, verbose_name='название')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartHomeApi.localimage')),
            ],
        ),
        migrations.AddField(
            model_name='userconfig',
            name='background',
            field=models.ManyToManyField(related_name='background', to='smartHomeApi.ImageBackground', verbose_name='фон'),
        ),
    ]
