# Generated by Django 3.1.5 on 2021-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0040_auto_20210331_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localimage',
            name='image',
            field=models.ImageField(upload_to='public', verbose_name='Изображение'),
        ),
    ]
