# Generated by Django 3.1.5 on 2021-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0041_auto_20210402_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartchildren',
            name='width',
            field=models.IntegerField(default=1, verbose_name='width'),
            preserve_default=False,
        ),
    ]
