# Generated by Django 3.1.5 on 2021-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0042_cartchildren_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecart',
            name='width',
            field=models.IntegerField(default=2, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='cartchildren',
            name='width',
            field=models.IntegerField(default=1, verbose_name='width'),
        ),
    ]
