# Generated by Django 3.1.5 on 2021-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0043_auto_20210419_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartchildren',
            name='height',
            field=models.IntegerField(default=1, verbose_name='width'),
        ),
    ]
