# Generated by Django 3.2.2 on 2021-05-24 16:23

from django.db import migrations
import bcrypt


class Migration(migrations.Migration):

    def base_user(apps, schema_editor):
        User = apps.get_model('smartHomeApi', 'User')
        UserConfig = apps.get_model('smartHomeApi', 'UserConfig')
        hashedPass = bcrypt.hashpw("admin",bcrypt.gensalt())
        newUser = User.objects.create(UserName="admin", UserEmail="sh@mail.ru", UserMobile=" ",UserPassword=hashedPass,UserLevel=3)
        newUser.save()
        newConf = UserConfig.objects.create(user=newUser)
        newConf.save()

    dependencies = [
        ('smartHomeApi', '0045_auto_20210508_1631'),
    ]

    operations = [
        migrations.RunPython(base_user),
    ]
