# Generated by Django 3.2.2 on 2021-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0046_auto_20210524_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerConfig',
        ),
        migrations.AlterField(
            model_name='usersconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
