# Generated by Django 3.2.2 on 2021-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0047_auto_20210525_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersConfig',
        ),
    ]
