# Generated by Django 3.2.2 on 2021-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0048_delete_usersconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='DeviceAddress',
            field=models.SlugField(default='', max_length=200, verbose_name='device address'),
        ),
        migrations.AddField(
            model_name='device',
            name='DeviceToken',
            field=models.SlugField(default='', max_length=200, verbose_name='device token'),
        ),
        migrations.AddField(
            model_name='device',
            name='DeviceValueType',
            field=models.SlugField(default='json', max_length=200, verbose_name='device value type'),
        ),
        migrations.AddField(
            model_name='valuedevice',
            name='address',
            field=models.SlugField(default='', max_length=200, verbose_name='device config address'),
        ),
        migrations.AddField(
            model_name='valuedevice',
            name='high',
            field=models.SlugField(default='255', max_length=200, verbose_name='device config high'),
        ),
        migrations.AddField(
            model_name='valuedevice',
            name='icon',
            field=models.SlugField(default='', max_length=200, verbose_name='device icon'),
        ),
        migrations.AddField(
            model_name='valuedevice',
            name='low',
            field=models.SlugField(default='0', max_length=200, verbose_name='device config low'),
        ),
        migrations.DeleteModel(
            name='ConfigDevice',
        ),
    ]
