# Generated by Django 3.2.2 on 2021-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0049_auto_20210528_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='DeviceStatus',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
