# Generated by Django 3.2.2 on 2021-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0050_device_devicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuedevice',
            name='typeControl',
            field=models.SlugField(default='boolean', max_length=200, verbose_name='device value value'),
        ),
        migrations.AlterField(
            model_name='device',
            name='DeviceStatus',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
    ]
