# Generated by Django 3.2.2 on 2021-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0051_auto_20210530_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuedevice',
            name='unit',
            field=models.CharField(default='', max_length=10, verbose_name='unit'),
        ),
    ]
