# Generated by Django 3.2.2 on 2021-06-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0052_valuedevice_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='scriptAct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actionScript', to='smartHomeApi.scripts'),
        ),
    ]
