# Generated by Django 3.2.2 on 2021-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0054_auto_20210609_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuedevice',
            name='control',
            field=models.BooleanField(default=True, verbose_name='управление'),
        ),
    ]
