# Generated by Django 3.2.2 on 2021-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0055_valuedevice_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuedevice',
            name='high',
            field=models.SlugField(default='', max_length=200, verbose_name='device config high'),
        ),
        migrations.AlterField(
            model_name='valuedevice',
            name='low',
            field=models.SlugField(default='', max_length=200, verbose_name='device config low'),
        ),
    ]
