# Generated by Django 3.2.2 on 2021-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0056_auto_20210609_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='ifblock',
            name='device',
        ),
        migrations.RemoveField(
            model_name='ifgroupblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='ifgroupblock',
            name='script',
        ),
        migrations.RemoveField(
            model_name='triger',
            name='device',
        ),
        migrations.RemoveField(
            model_name='triger',
            name='script',
        ),
        migrations.RemoveField(
            model_name='value',
            name='actBlock',
        ),
        migrations.RemoveField(
            model_name='value',
            name='device',
        ),
        migrations.RemoveField(
            model_name='value',
            name='ifBlock',
        ),
        migrations.RemoveField(
            model_name='value',
            name='valuefirst',
        ),
        migrations.RemoveField(
            model_name='value',
            name='valuesecond',
        ),
        migrations.AlterField(
            model_name='valuedevice',
            name='type',
            field=models.SlugField(default='binary', max_length=200, verbose_name='device value value'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='IfBlock',
        ),
        migrations.DeleteModel(
            name='IfGroupBlock',
        ),
        migrations.DeleteModel(
            name='Scripts',
        ),
        migrations.DeleteModel(
            name='Triger',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
