# Generated by Django 3.2.2 on 2021-07-01 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0057_auto_20210629_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuelistdevice',
            name='type',
        ),
        migrations.AddField(
            model_name='valuelistdevice',
            name='name',
            field=models.SlugField(default=4, max_length=200, verbose_name='device name field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valuelistdevice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 10, 11, 56, 865988), verbose_name='device value element date'),
        ),
        migrations.AlterField(
            model_name='valuelistdevice',
            name='value',
            field=models.SlugField(default='', max_length=200, verbose_name='device value list value'),
        ),
    ]
