# Generated by Django 3.2.2 on 2021-07-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0058_auto_20210701_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelistdevice',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='device value element date'),
        ),
    ]
