# Generated by Django 3.2.2 on 2021-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0059_alter_valuelistdevice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecart',
            name='homePage',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='page',
            field=models.CharField(default='basePage', max_length=200, verbose_name='activePage'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='Style',
            field=models.CharField(default='light', max_length=200, verbose_name='style'),
        ),
        migrations.DeleteModel(
            name='CartChildren',
        ),
        migrations.DeleteModel(
            name='HomeCart',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
