# Generated by Django 3.2.2 on 2021-12-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHomeApi', '0060_auto_20211003_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuedevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='valuelistdevice',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='ValueDevice',
        ),
        migrations.DeleteModel(
            name='ValueListDevice',
        ),
    ]
