# Generated by Django 3.1.5 on 2021-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceId', models.IntegerField(verbose_name='id device')),
                ('DeviceName', models.CharField(max_length=200, verbose_name='device name')),
                ('DeviceSystemName', models.CharField(max_length=200, verbose_name='device system name')),
                ('DeviceInformation', models.TextField(verbose_name='user config')),
                ('DeviceTypeConnect', models.CharField(max_length=200, verbose_name='device type connect')),
                ('DeviceType', models.CharField(max_length=200, verbose_name='device type')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(verbose_name='id user')),
                ('UserName', models.CharField(max_length=200, verbose_name='user name')),
                ('UserPassword', models.CharField(max_length=200, verbose_name='user password')),
                ('UserEmail', models.EmailField(max_length=254, verbose_name='user email')),
                ('UserMobile', models.CharField(max_length=200, verbose_name='user mobile')),
                ('UserLevel', models.IntegerField(verbose_name='user level')),
            ],
        ),
    ]
