# Generated by Django 3.1.5 on 2021-01-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='DeviceId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserId',
        ),
    ]
