# Generated by Django 3.1.5 on 2021-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20210123_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserSurname',
            field=models.CharField(default='', max_length=200, verbose_name='user surname'),
            preserve_default=False,
        ),
    ]
