# Generated by Django 3.1.5 on 2021-01-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_user_usersurname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('Style', models.CharField(max_length=200, verbose_name='user name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smarthome.user')),
            ],
        ),
    ]
