# Generated by Django 3.1.5 on 2021-01-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_userconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserLevel',
            field=models.IntegerField(default=1, verbose_name='user level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserSurname',
            field=models.CharField(default='', max_length=200, verbose_name='user surname'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='Style',
            field=models.CharField(default='light', max_length=200, verbose_name='user name'),
        ),
    ]
