# Generated by Django 3.1.5 on 2021-01-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0005_auto_20210125_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteStyle', models.NullBooleanField(default=True, verbose_name='automatic style')),
                ('staticBackground', models.NullBooleanField(default=False, verbose_name='static background')),
                ('updateFrequency', models.IntegerField(default=10, verbose_name='time update')),
                ('mqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker address')),
                ('loginMqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker login')),
                ('passwordMqttBroker', models.CharField(default='', max_length=200, verbose_name='mqttBroker password')),
            ],
        ),
    ]
