export const data = {
  light:{
    config:[
      {
        address:"",
        name:"state",
        type:"binary",
        low:"0",
        high:"1",
        values:"",
        control:true,
        icon:""
      },
      {
        address:"",
        name:"brightness",
        type:"number",
        low:"0",
        high:"100",
        values:"",
        control:true,
        icon:""
      },
      {
        address:"",
        name:"color",
        type:"number",
        low:"0",
        high:"255",
        values:"",
        control:true,
        icon:""
      },
      {
        address:"",
        name:"temp",
        type:"number",
        low:"2600",
        high:"3200",
        values:"",
        control:true,
        icon:""
      },
      {
        address:"",
        name:"mode",
        type:"binary",
        low:"0",
        high:"1",
        values:"",
        control:true,
        icon:""
      },
    ],
    editCountField:false,
    typeControl:"control",
    editType:false,
    editTypeControl:false
  },
  relay:{
    config:[
      {
        address:"",
        name:"state",
        type:"binary",
        low:"0",
        high:"1",
        values:"",
        control:true,
        icon:""
      },
    ],
    editCountField:false,
    typeControl:"control",
    editTypeControl:false,
    editType:false,
  },
  dimmer:{
    config:[
      {
        address:"",
        name:"state",
        type:"binary",
        low:"0",
        high:"1",
        values:"",
        control:true,
        icon:""
      },
      {
        address:"brightness",
        name:"brightness",
        type:"number",
        low:"0",
        high:"100",
        values:"",
        control:true,
        icon:""
      },
    ],
    editCountField:false,
    editTypeControl:false,
    editType:false,
    typeControl:"control"
  },
  sensor:{
    config:[
      {
        address:"sn1",
        name:"sn1",
        type:"number",
        low:"0",
        high:"100",
        values:"",
        control:false,
        icon:""
      }
    ],
    editCountField:true,
    editTypeControl:true,
    editType:true,
    typeControl:"sensor"
  },
  other:{
    config:[
      {
        address:"field0",
        name:"field0",
        type:"text",
        low:"0",
        high:"100",
        values:"",
        control:true,
        icon:""
      }
    ],
    editCountField:true,
    editTypeControl:true,
    editType:true,
    typeControl:"all"
  }
}

export const getConf = (type)=>data[type]||data.other
