export const data = {
  light:{
    config:[
      {
        address:"",
        type:"state",
        typeControl:"boolean",
        low:"0",
        high:"1",
        icon:""
      },
      {
        address:"",
        type:"brightness",
        typeControl:"range",
        low:"0",
        high:"100",
        icon:""
      },
      {
        address:"",
        type:"color",
        typeControl:"range",
        low:"0",
        high:"255",
        icon:""
      },
      {
        address:"",
        type:"temp",
        typeControl:"range",
        low:"2600",
        high:"3200",
        icon:""
      },
      {
        address:"",
        type:"mode",
        typeControl:"number",
        low:"0",
        high:"2",
        icon:""
      },
    ],
    editCountField:false,
    typeControl:"control",
    editType:false,
    editTypeControl:false
  },
  relay:{
    config:[
      {
        address:"",
        type:"state",
        typeControl:"boolean",
        low:"0",
        high:"1",
        icon:""
      },
    ],
    editCountField:false,
    typeControl:"control",
    editTypeControl:false,
    editType:false,
  },
  dimmer:{
    config:[
      {
        address:"",
        type:"state",
        typeControl:"boolean",
        low:"0",
        high:"1",
        icon:""
      },
      {
        address:"brightness",
        type:"brightness",
        typeControl:"range",
        low:"0",
        high:"100",
        icon:""
      },
    ],
    editCountField:false,
    editTypeControl:false,
    editType:false,
    typeControl:"control"
  },
  sensor:{
    config:[
      {
        address:"sn1",
        type:"sn1",
        typeControl:"sensor",
        low:"0",
        high:"100",
        icon:""
      }
    ],
    editCountField:true,
    editTypeControl:true,
    editType:true,
    typeControl:"sensor"
  },
  other:{
    config:[
      {
        address:"field0",
        type:"field0",
        typeControl:"text",
        low:"0",
        high:"100",
        icon:""
      }
    ],
    editCountField:true,
    editTypeControl:true,
    editType:true,
    typeControl:"all"
  }
}

export const getConf = (type)=>data[type]||data.other
