version: '3.8'
services:
  mqtt_page:
    container_name: mqtt_page
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTAINER_NAME: mqtt_page
        PORT: 3000
        NEXT_BASE_PATH: /modules/mqtt_page
    command: sh -c "cp -r /app/config_local/* /app/config && npm run start"
    restart: always
    environment:
      EXCHANGE_SERVICE_DATA: ${EXCHANGE_SERVICE_DATA}
      RABITMQ_PORT: ${RABITMQ_PORT}
      RABITMQ_HOST: ${RABITMQ_HOST}
      CONTAINER_NAME: mqtt_page
      PORT: 3000
    labels:
    - traefik.http.routers.mqtt_page__ws.rule=PathPrefix(`/ws/mqtt_page`)
    - traefik.http.routers.mqtt_page__ws.service=mqtt_page__ws
    - traefik.http.services.mqtt_page__ws.loadbalancer.server.port=3000
    - traefik.http.routers.mqtt_page__ws.entrypoints=websecure
    - traefik.enable=true
    - traefik.http.routers.mqtt_page_http.rule=PathPrefix(`/modules/mqtt_page`)
    - traefik.http.routers.mqtt_page_http.entrypoints=web
    - traefik.http.routers.mqtt_page_http.middlewares=moduleauth@docker,module-mqtt_page-strip
    - traefik.http.routers.mqtt_page_http.service=mqtt_page
    - traefik.http.routers.mqtt_page_https.rule=PathPrefix(`/modules/mqtt_page`)
    - traefik.http.routers.mqtt_page_https.entrypoints=websecure
    - traefik.http.routers.mqtt_page_https.middlewares=moduleauth@docker,module-mqtt_page-strip
    - traefik.http.routers.mqtt_page_https.tls=true
    - traefik.http.routers.mqtt_page_https.service=mqtt_page
    - traefik.http.services.mqtt_page.loadbalancer.server.port=3000
    - traefik.http.middlewares.module-mqtt_page-strip.stripprefixregex.regex=^/modules/mqtt_page
    volumes:
    - ${CONFIGURATE_DIR}/mqtt_page:/app/config
    networks:
    - local_sh_network
networks:
  local_sh_network:
    name: ${NETWORK_NAME}
    external: true
