cards:
- children:
  - height: 2
    index: 0
    name: weather
    order: 0
    type: weather
    width: 4
  index: 0
  mainId: null
  name: "\u043F\u043E\u0433\u043E\u0434\u0430"
  order: '0'
  type: base
  width: 2
- children:
  - height: 2
    index: 0
    name: date
    order: 0
    type: date
    width: 4
  - height: 1
    index: 1
    name: time
    order: '0'
    type: time
    width: 2
  - deviceId: 2
    height: 1
    index: 2
    name: zigbee2mqtt
    order: 0
    title: stick
    type: sensor
    typeAction: state
    width: 1
  index: 1
  mainId: null
  name: ''
  order: '0'
  type: base
  width: 2
- children:
  - deviceName: lamp1
    height: 1
    index: 0
    name: "\u043B\u0430\u043C\u043F\u0430 \u0432 \u0441\u043F\u0430\u043B\u044C\u043D\
      \u0435"
    order: 0
    title: "\u0441\u0432\u0435\u0442"
    type: button
    typeAction: state
    width: 1
  - deviceName: lamp1
    height: 1
    index: 1
    name: "\u043B\u0430\u043C\u043F\u0430 \u0432 \u0441\u043F\u0430\u043B\u044C\u043D\
      \u0435"
    order: 0
    title: "\u044F\u0440\u043A\u043E\u0441\u0442\u044C"
    type: slider
    typeAction: brightness
    width: 1
  - deviceName: magicCub
    height: 1
    index: 2
    name: "\u043A\u0443\u0431"
    order: 0
    title: cub
    type: sensor
    typeAction: action_angle
    width: 1
  - deviceName: switch1
    height: 1
    index: 3
    name: switch1
    order: 0
    title: btn1
    type: button
    typeAction: left
    width: 1
  index: 2
  mainId: null
  name: ''
  order: '0'
  type: base
  width: 2
- children:
  - deviceName: testdev
    height: 1
    index: 0
    name: testdev
    order: 0
    title: test test
    type: text
    typeAction: field1
    width: 1
  index: 3
  mainId: null
  name: ''
  order: '0'
  type: line
  width: 2
name: basePage
