cards:
- children:
  - height: 2
    index: 0
    name: weather
    order: 0
    type: weather
    width: 4
  index: 0
  mainId: null
  name: "\u043F\u043E\u0433\u043E\u0434\u0430"
  order: '0'
  type: base
  width: 2
- children:
  - deviceId: 8
    height: 1
    index: 0
    name: "\u041B\u0430\u043C\u043F\u0430 \u0432 \u0441\u043F\u0430\u043B\u044C\u043D\
      \u0435"
    order: 0
    title: "\u0441\u0432\u0435\u0442"
    type: button
    typeAction: state
    width: 1
  - deviceId: 8
    height: 1
    index: 1
    name: "\u041B\u0430\u043C\u043F\u0430 \u0432 \u0441\u043F\u0430\u043B\u044C\u043D\
      \u0435"
    order: 0
    title: "\u0443\u0440\u043E\u0432\u0435\u043D\u044C \u0441\u0432\u0435\u0442\u0430"
    type: slider
    typeAction: brightness
    width: 1
  index: 1
  mainId: null
  name: "\u0441\u043F\u0430\u043B\u044C\u043D\u044F"
  order: '0'
  type: line
  width: 2
name: basePage
