cards:
- children:
  - height: 2
    index: 0
    name: weather
    order: 0
    type: weather
    width: 4
  index: 0
  mainId: null
  name: "\u043F\u043E\u0433\u043E\u0434\u0430"
  order: '0'
  type: base
  width: 2
name: basePage
