cards:
- deviceId: null
  height: 1
  id: 4
  name: test
  poz: 1
  type: test
  typeAction: null
  width: 1
- deviceId: null
  height: 1
  id: 1
  name: test
  poz: 5
  type: test
  typeAction: null
  width: 1
- deviceId: null
  height: 1
  id: 5
  name: test
  poz: 2
  type: test
  typeAction: null
  width: 1
- deviceId: null
  height: 1
  id: 3
  name: test
  poz: 3
  type: test
  typeAction: null
  width: 1
- deviceId: null
  height: 1
  id: 2
  name: test
  poz: 4
  type: test
  typeAction: null
  width: 1
name: page1
