cards:
- children:
  - deviceId: 2
    height: 1
    index: 0
    name: zigbee2mqtt
    order: 0
    type: sensor
    typeAction: state
    width: 1
  index: 0
  mainId: null
  name: ''
  order: '0'
  type: base
  width: 2
name: page1
