services:
  mqtt_page:
    container_name: mqtt_page
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTAINER_NAME: mqtt_page
        PORT: 3000
        NEXT_BASE_PATH: "/modules/mqtt_page"
    command: sh -c "cp -r /app/config_local/* /app/config && npm run start"
    restart: always
    networks: 
      - local_sh_network
    environment:
      RMQ_HOST: ${RABITMQ_HOST}
      RMQ_PORT: ${RABITMQ_PORT}
      EXCHANGE_SERVICE_DATA: ${EXCHANGE_SERVICE_DATA}
    labels:
      - "traefik.enable=true"
      # http (без TLS)
      - "traefik.http.routers.mqtt_http.rule=PathPrefix(`/modules/mqtt_page`)"
      - "traefik.http.routers.mqtt_http.entrypoints=web"
      - "traefik.http.routers.mqtt_http.middlewares=moduleauth@docker,module-mqtt_page-strip"
      - "traefik.http.routers.mqtt_http.service=mqtt"
      # https (с TLS)
      - "traefik.http.routers.mqtt_https.rule=PathPrefix(`/modules/mqtt_page`)"
      - "traefik.http.routers.mqtt_https.entrypoints=websecure"
      - "traefik.http.routers.mqtt_https.middlewares=moduleauth@docker,module-mqtt_page-strip"
      - "traefik.http.routers.mqtt_https.tls=true"
      - "traefik.http.routers.mqtt_https.service=mqtt"
      # websocket
      - "traefik.http.routers.mqtt_page_ws.rule=PathPrefix(`/ws/mqtt_page`)"
      - "traefik.http.routers.mqtt_page_ws.service=mqtt_page_ws"
      - "traefik.http.services.mqtt_page_ws.loadbalancer.server.port=3000"
      - "traefik.http.routers.mqtt_page_ws.entrypoints=websecure"
      # общий сервис
      - "traefik.http.services.mqtt.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.module-mqtt_page-strip.stripprefixregex.regex=^/modules/mqtt_page"
    volumes:
      - ${CONFIGURATE_DIR}/mqtt_page:/app/config

networks:
  local_sh_network:
    name: ${NETWORK_NAME}
    external: true