"""init

Revision ID: c1c00079f3e0
Revises: 
Create Date: 2024-10-19 12:05:06.106692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c00079f3e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', name='uc_roles_role_name')
    )
    op.create_table('roleprivileges',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('privilege', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_roleprivileges_roles_id_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('privilege', name='uc_roleprivileges_privilege')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_users_roles_id_role', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uc_users_name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('access', sa.Text(), nullable=False),
    sa.Column('refresh', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_sessions_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access', 'refresh', name='uc_sessions_access_refresh')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('roleprivileges')
    op.drop_table('roles')
    # ### end Alembic commands ###
