# Generated by Django 3.1.5 on 2021-03-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='grade',
            field=models.CharField(default='', max_length=150, verbose_name='качество'),
        ),
        migrations.AddField(
            model_name='movie',
            name='loaded',
            field=models.BooleanField(default=False, verbose_name='загруженно'),
        ),
    ]
