# Generated by Django 3.1.5 on 2021-03-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210318_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.movie')),
                ('count_seasons', models.PositiveSmallIntegerField(default=1, verbose_name='количество сезонов')),
                ('closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('save_seasons', models.PositiveSmallIntegerField(default=0, verbose_name='сохранено сезонов')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
            bases=('files.movie',),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='discription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='url',
            field=models.SlugField(default=None, max_length=160, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movieganre',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
