# Generated by Django 3.1.5 on 2021-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20210319_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='discription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='discription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movieganre',
            name='discription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='discription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
