# Generated by Django 3.1.5 on 2021-03-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20210319_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
