# Generated by Django 3.1.5 on 2021-03-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_delete_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
