# Generated by Django 3.1.5 on 2021-03-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20210320_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieShots',
        ),
    ]
