# Generated by Django 3.1.5 on 2021-03-20 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_delete_movieshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=150, verbose_name='Слоган')),
                ('discription', models.TextField(default='', verbose_name='Описание')),
                ('poster', models.ImageField(null=True, upload_to='files/movie/posters/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='примьера в мире')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='сборы в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='сборы в мире')),
                ('url', models.SlugField(default=None, max_length=160, null=True, unique=True)),
                ('localUrl', models.SlugField(default=None, max_length=160, null=True, unique=True)),
                ('grade', models.CharField(default='', max_length=150, verbose_name='качество')),
                ('loaded', models.BooleanField(default=False, verbose_name='загруженно')),
                ('draft', models.BooleanField(default=False, verbose_name='черновик')),
                ('actors', models.ManyToManyField(related_name='movie_film_actor', to='files.MovieActor', verbose_name='актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.moviecategory', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='movie_film_director', to='files.MovieActor', verbose_name='режиссер')),
                ('genres', models.ManyToManyField(to='files.MovieGanre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=150, verbose_name='Слоган')),
                ('discription', models.TextField(default='', verbose_name='Описание')),
                ('poster', models.ImageField(null=True, upload_to='files/movie/posters/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='примьера в мире')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='сборы в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='указать сумму в доллорах', verbose_name='сборы в мире')),
                ('url', models.SlugField(default=None, max_length=160, null=True, unique=True)),
                ('localUrl', models.SlugField(default=None, max_length=160, null=True, unique=True)),
                ('grade', models.CharField(default='', max_length=150, verbose_name='качество')),
                ('loaded', models.BooleanField(default=False, verbose_name='загруженно')),
                ('draft', models.BooleanField(default=False, verbose_name='черновик')),
                ('count_seasons', models.PositiveSmallIntegerField(default=1, verbose_name='количество сезонов')),
                ('closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('save_seasons', models.PositiveSmallIntegerField(default=0, verbose_name='сохранено сезонов')),
                ('actors', models.ManyToManyField(related_name='serial_film_actor', to='files.MovieActor', verbose_name='актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.moviecategory', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='serial_film_director', to='files.MovieActor', verbose_name='режиссер')),
                ('genres', models.ManyToManyField(to='files.MovieGanre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('discription', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='files/movie/shots/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.movie', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'кадр из фильма',
                'verbose_name_plural': 'кадры из фильма',
            },
        ),
    ]
