# Generated by Django 3.1.5 on 2021-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20210402_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='localUrl',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='url',
            field=models.URLField(default=None, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='url',
            field=models.URLField(max_length=160),
        ),
        migrations.AlterField(
            model_name='movieganre',
            name='url',
            field=models.URLField(max_length=160),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='serial',
            name='localUrl',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
