# Generated by Django 3.1.5 on 2021-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20210403_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='localUrl',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='локальная ссылка'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='localUrl',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='локальная ссылка'),
        ),
    ]
