else: []
if:
  action: null
  children:
  - action: action
    idDevice: 6
    oper: ==
    type: device
    value:
      type: enum
      value: flip90
  idDevice: null
  oper: and
  type: group
  value: null
name: target_lamp_by_cube
status: true
then:
- DeviceId: togle
  action: run
  type: script
trigger:
- DeviceId: 6
  action: action
  type: device
