else: []
if:
  action: null
  children:
  - action: field1binary
    idDevice: 5
    oper: ==
    type: device
    value:
      type: enum
      value: high
  idDevice: null
  oper: and
  type: group
  value: null
name: testnew
status: true
then:
- DeviceId: togle
  action: run
  type: script
trigger:
- DeviceId: 5
  action: field1binary
  type: device
