else: []
if:
  action: null
  children: []
  idDevice: null
  oper: and
  type: group
  value: null
name: test3
status: false
then:
- DeviceId: 8
  action: brightness
  type: device
  value:
    action: '-'
    type: math
    value1:
      action: brightness
      idDevice: 8
      type: device
    value2:
      type: number
      value: '10'
trigger: []
