else:
- DeviceId: 4
  action: state
  type: device
  value:
    type: enum
    value: low
if:
  action: null
  children:
  - action: state
    idDevice: 4
    oper: ==
    type: device
    value:
      type: enum
      value: low
  idDevice: null
  oper: and
  type: group
  value: null
name: togle
status: false
then:
- DeviceId: 4
  action: state
  type: device
  value:
    type: enum
    value: high
trigger: []
