else: []
if:
  action: null
  children: []
  idDevice: null
  oper: and
  type: group
  value: null
name: tst5
status: false
then:
- DeviceId: 4
  action: state
  type: device
  value:
    type: enum
    value: togle
trigger: []
