from moduls_src.pages import *
from .linc import lincDecice

def page():
    return Pages(
        name="mqtt",
        linc=lincDecice,
        pages=[Page(
            name="mqtt",
            menu=[
                MenuFieldSchema(
                    title=fieldSRC(
                        type="text",
                        value="update"
                    ),
                    action=[
                        ActionSchema(type="update"),
                    ]
                ),
                MenuFieldSchema(
                    title=fieldSRC(
                        type="text",
                        value="clear"
                    ),
                    action=[
                        ActionSchema(
                            address="/api/module/mqtt/clear",
                        ),
                        ActionSchema(type="update"),
                    ]
                )
            ],
            src="/api/module/mqtt/get",
            ws_src="mqtt",
            content=TableContent(
                items=Table(
                    title=fieldSRC(
                        type="text",
                        value="test"
                    ),
                    fields=[
                    TableFields(
                        title="address",
                        value=fieldSRC(
                            type="path",
                            path=".topic"
                        )
                    ),
                    TableFields(
                        title="message",
                        type=TypeField.JSON,
                        value=fieldSRC(
                            type="path",
                            path=".message"
                        )
                    )],
                    menu=[MenuFieldSchema(
                        title=fieldSRC(
                            type="text",
                            value="linc"
                        ),
                        action=[
                            ActionSchema(type=TypeAction.LINC),
                        ]
                    )]
                )
            )
        )]
    )
