from django.urls import path,re_path
from . import views

urlpatterns = [
    path('auth/login',views.LoginView.as_view()),
    path('server/config',views.ServerConfigView.as_view()),
    path('server/data',views.ServerData.as_view()),
    path('user/config',views.UserConfigView.as_view()),
    path('user',views.UserView.as_view()),
    path('user/menu',views.MenuView.as_view()),
    path('user/page',views.UserSetPage.as_view()),
    path('users',views.UsersView.as_view()),
    path('users/<int:id>/level',views.UserLevel.as_view()),
    path('user/edit/password',views.UserEditPassword.as_view()),
    path('user/newpass',views.UserNewPassword.as_view()),
    path('user/style/add',views.CreateStyle.as_view()),
    path('user/style/remove',views.RemoveStyle.as_view()),
    path('user/styles',views.Style.as_view()),
    path('devices/<int:id>',views.DeviceGetDeleteView.as_view()),
    path('devices',views.DevicePutPostView.as_view()),
    path('devices/value/set',views.SetValueDevice.as_view()),
    path('devices/status/set',views.SetStatusDevice.as_view()),
    path('charts/get',views.GetCharts.as_view()),
    path('mqtt',views.MqttDevice.as_view()),
    path('mqtt/clear',views.MqttClear.as_view()),
    path('zigbee2mqtt/reboot',views.Zigbee2mqttReboot.as_view()),
    path('zigbee2mqtt/permit_join',views.Zigbee2mqttPermJoin.as_view()),
    path('zigbee2mqtt/devices',views.Zigbee2mqttDevice.as_view()),
    path('zigbee2mqtt/rename',views.Zigbee2mqttRename.as_view()),
    # path('zigbee2mqtt/device',views.Zigbee2mqttDelete.as_view()),
    path('homePage/get/<str:name>',views.GetHomePageView.as_view()),
    path('homePage/set',views.SetHomePage.as_view()),
    path('homePage/add',views.AddHomePage.as_view()),
    path('homePage/delete',views.DeleteHomePage.as_view()),
    path('script/all',views.GetScripts.as_view()),
    path('script/<str:name>',views.ScriptGetDeletePutView.as_view()),
    path('script',views.ScriptPostView.as_view()),
    path('script/set/status',views.SetStatusScript.as_view()),
    path('script/run/<str:name>',views.RunScript.as_view()),
    path('image/<str:type>/<int:id>',views.ImageView.as_view()),
    path('image/<str:type>/el/<int:index>',views.GetTenUrl.as_view()),
    path('background/set',views.linkBackgroundView.as_view()),
    path('media/set/image/<str:name>',views.SetBackground.as_view()),
]
