from django.urls import path,re_path
from . import views

urlpatterns = [
    path('auth/login',views.LoginView.as_view()),
    path('server/config',views.ServerConfigView.as_view()),
    path('server/config/edit',views.ServerConfigEditView.as_view()),
    path('server/usersConfig/edit',views.EditUsersConfigView.as_view()),
    path('server/usersConfig',views.GetUserConfigView.as_view()),
    path('server/data/get',views.GetServerData.as_view()),
    path('user/config/edit',views.EditUserConfigView.as_view()),
    path('user/config',views.ClientConfigView.as_view()),
    path('user',views.GetUserView.as_view()),
    path('user/edit',views.EditUserView.as_view()),
    path('user/menu/edit',views.EditMenuView.as_view()),
    path('users/get',views.GetUsers.as_view()),
    path('users/delete',views.DeleteUser.as_view()),
    path('users/<int:id>/edit/level',views.EditUserLevel.as_view()),
    path('user/add',views.AddUserView.as_view()),
    path('user/edit/password',views.UserEditPassword.as_view()),
    path('user/newpass',views.UserNewPassword.as_view()),
    path('devices/add',views.AddDevice.as_view()),
    path('devices/get/<int:id>',views.GetDevice.as_view()),
    path('devices/edit',views.EditDevice.as_view()),
    path('devices/delete',views.DeleteDevice.as_view()),
    path('devices/value/set',views.SetValueDevice.as_view()),
    path('devices/get/mqtt',views.GetMqttDevice.as_view()),
    path('homeCart/get/<int:id>',views.GetHomePageView.as_view()),
    path('homeCart/set',views.SetHomePage.as_view()),
    path('script/add',views.AddScript.as_view()),
    path('script/all',views.GetScripts.as_view()),
    path('script/get/<int:id>',views.GetScript.as_view()),
    path('script/edit/<int:id>',views.EditScript.as_view()),
    path('script/delete',views.DeleteScript.as_view()),
    path('script/set/status',views.SetStatusScript.as_view()),
    path('script/run/<int:id>',views.RunScript.as_view()),
    path('image/<str:type>/delete',views.DeleteImage.as_view()),
    path('image/<str:type>/<int:index>',views.GetTenUrl.as_view()),
    path('background/set',views.linkBackgroundView.as_view()),
    path('media/set/image/<str:name>',views.SetBackground.as_view()),
]
