from django.urls import path,re_path
from . import views

urlpatterns = [
    path('auth/register',views.register),
    path('auth/login',views.login),
    path('server/config',views.serverConfig),
    path('server/config/edit',views.clientConfigedit),
    path('server/usersConfig/edit',views.editUsersConf),
    path('server/usersConfig',views.giveUserConf),
    path('user/config/edit',views.edituserconf),
    path('user/config',views.clientConfig),
    path('user',views.giveuser),
    path('user/edit',views.edituser),
    path('user/menu/edit',views.editmenu),
    path('users/get',views.giveusers),
    path('users/delete',views.deleteuser),
    path('user/add',views.addNewUser),
    path('devices/add',views.deviceAdd),
    # path('devices/all',views.devicesGive),
    path('devices/get/<int:id>',views.deviceGive),
    path('devices/edit',views.deviceEdit),
    path('devices/delete',views.deviceDelete),
    path('devices/value/set',views.deviceSetValue),
    path('homeCart/get/<int:id>',views.getHomeCart),
    path('homeCart/set',views.setHomeCart),
    path('script/add',views.addScript),
    path('script/all',views.getScripts),
    path('script/get/<int:id>',views.getScript),
    path('script/edit/<int:id>',views.editScript),
    path('script/delete',views.deleteScript),
    path('script/set/status',views.setStatusScript),
    path('script/run/<int:id>',views.runScript),
    path('image/<str:type>/delete',views.deleteImg),
    path('image/<str:type>/<int:index>',views.getTenUrl),
    # path('home/value/set',views.deviceSetValue),
    # path('media/set/<slug:name>/', views.media)
    # path('devices/all',views.allDevices),
    # path('base/fonImage',views.fonImage),
    path('media/set/image/<str:name>',views.setBackground),
]
# /api/media/set/
