"""Added session table

Revision ID: 04364195987c
Revises: 3f5ef5983d64
Create Date: 2022-09-04 20:53:05.752493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04364195987c'
down_revision = '3f5ef5983d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('access', sa.Text(), nullable=False),
    sa.Column('refrash', sa.Text(), nullable=False),
    sa.Column('access_oauth', sa.Text(), nullable=True),
    sa.Column('refrash_oauth', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('devicehistorys', 'unit',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_column('users', 'auteStyle')
    op.drop_column('users', 'staticBackground')
    op.drop_column('users', 'Style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Style', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('users', sa.Column('staticBackground', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auteStyle', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('devicehistorys', 'unit',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_table('sessions')
    # ### end Alembic commands ###
