"""session

Revision ID: 0d2843680273
Revises: 5deb10093bce
Create Date: 2022-10-09 15:33:14.437223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d2843680273'
down_revision = '5deb10093bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key('fk_sessions_users_id_user', 'sessions', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_users_id_user', 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'user',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
