"""historyupdate

Revision ID: 19ed3d5a3df3
Revises: 33647b0b8b64
Create Date: 2022-02-23 13:31:18.710906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ed3d5a3df3'
down_revision = '33647b0b8b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
