"""init

Revision ID: 1b60669ad550
Revises: 
Create Date: 2025-03-27 19:45:25.106874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b60669ad550'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition_type', sa.Enum('AND', 'OR', name='conditiontype'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('devices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('class_device', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('type_command', sa.String(length=200), nullable=True),
    sa.Column('type_get_data', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('system_name')
    )
    op.create_table('typedevices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actionelseitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=400), nullable=False),
    sa.Column('type_set', sa.String(length=10), nullable=True),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_actionelseitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actionitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=400), nullable=False),
    sa.Column('type_set', sa.String(length=10), nullable=True),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_actionitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditionitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.Column('arg1_service', sa.String(length=200), nullable=False),
    sa.Column('arg1_object', sa.String(length=200), nullable=True),
    sa.Column('arg1_data', sa.String(length=200), nullable=False),
    sa.Column('arg2_service', sa.String(length=200), nullable=False),
    sa.Column('arg2_object', sa.String(length=200), nullable=True),
    sa.Column('arg2_data', sa.String(length=200), nullable=False),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_conditionitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicefields',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('low', sa.String(length=200), nullable=True),
    sa.Column('high', sa.String(length=200), nullable=True),
    sa.Column('enum_values', sa.String(length=200), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('virtual_field', sa.Boolean(), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['devices.system_name'], name='fk_devicefields_devices_system_name_device', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fieldtypedevices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('name_field_type', sa.String(length=100), nullable=False),
    sa.Column('id_field_device', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['device'], ['typedevices.id'], name='fk_fieldtypedevices_typedevices_id_device', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targetitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_targetitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('datatime', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['devicefields.id'], name='fk_values_devicefields_id_field', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    op.drop_table('targetitems')
    op.drop_table('fieldtypedevices')
    op.drop_table('devicefields')
    op.drop_table('conditionitems')
    op.drop_table('actionitems')
    op.drop_table('actionelseitems')
    op.drop_table('typedevices')
    op.drop_table('devices')
    op.drop_table('automations')
    # ### end Alembic commands ###
