"""value auto id

Revision ID: 1cec96a59c6f
Revises: 47f2bc3f2444
Create Date: 2023-09-30 21:40:19.716504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cec96a59c6f'
down_revision = '47f2bc3f2444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
