"""trigger

Revision ID: 24b791ff3399
Revises: 413012d789ef
Create Date: 2023-12-24 11:54:59.652301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b791ff3399'
down_revision = '413012d789ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('trigger_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_entity', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=300), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['trigger'], ['triggers.name'], name='fk_trigger_actions_triggers_name_trigger', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_entity', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=300), nullable=False),
    sa.Column('sign', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['trigger'], ['triggers.name'], name='fk_trigger_conditions_triggers_name_trigger', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_entitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_entity', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=300), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['trigger'], ['triggers.name'], name='fk_trigger_entitys_triggers_name_trigger', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_entitys')
    op.drop_table('trigger_conditions')
    op.drop_table('trigger_actions')
    op.drop_table('triggers')
    # ### end Alembic commands ###
