"""device_type_2

Revision ID: 2c8a2e51e354
Revises: 492d68aa4e84
Create Date: 2025-03-28 12:50:26.149479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8a2e51e354'
down_revision: Union[str, None] = '492d68aa4e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fieldtypedevices', sa.Column('description', sa.String(length=300), nullable=False))
    op.add_column('fieldtypedevices', sa.Column('required', sa.Boolean(), nullable=False))
    op.add_column('fieldtypedevices', sa.Column('field_type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fieldtypedevices', 'field_type')
    op.drop_column('fieldtypedevices', 'required')
    op.drop_column('fieldtypedevices', 'description')
    # ### end Alembic commands ###
