"""user_auth_accaunt

Revision ID: 3d704de748a7
Revises: 6ed69520ead1
Create Date: 2022-10-07 20:41:41.450718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d704de748a7'
down_revision = '6ed69520ead1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_service_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_service_name')
    # ### end Alembic commands ###
