"""automation is_enable

Revision ID: 407a54539c4e
Revises: 92cccb10c3c7
Create Date: 2025-02-10 22:37:42.953076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '407a54539c4e'
down_revision: Union[str, None] = '92cccb10c3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.alter_column('automations', 'condition_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('AND', 'OR', name='conditiontype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('automations', 'condition_type',
               existing_type=sa.Enum('AND', 'OR', name='conditiontype'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('automations', 'is_enabled')
    # ### end Alembic commands ###
