"""cascad

Revision ID: 47f2bc3f2444
Revises: 86f8b56ceecb
Create Date: 2023-09-30 19:48:26.663309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f2bc3f2444'
down_revision = '86f8b56ceecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_device_fields_devices_system_name_device', 'device_fields', type_='foreignkey')
    op.create_foreign_key('fk_device_fields_devices_system_name_device', 'device_fields', 'devices', ['device'], ['system_name'], ondelete='CASCADE')
    op.drop_constraint('fk_values_device_fields_id_field', 'values', type_='foreignkey')
    op.create_foreign_key('fk_values_device_fields_id_field', 'values', 'device_fields', ['field'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_values_device_fields_id_field', 'values', type_='foreignkey')
    op.create_foreign_key('fk_values_device_fields_id_field', 'values', 'device_fields', ['field'], ['id'])
    op.drop_constraint('fk_device_fields_devices_system_name_device', 'device_fields', type_='foreignkey')
    op.create_foreign_key('fk_device_fields_devices_system_name_device', 'device_fields', 'devices', ['device'], ['system_name'])
    # ### end Alembic commands ###
