"""device_type

Revision ID: 492d68aa4e84
Revises: 1b60669ad550
Create Date: 2025-03-28 12:37:56.626112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '492d68aa4e84'
down_revision: Union[str, None] = '1b60669ad550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fieldtypedevices', sa.Column('device_type', sa.String(length=100), nullable=True))
    op.drop_constraint('fk_fieldtypedevices_typedevices_id_device', 'fieldtypedevices', type_='foreignkey')
    op.create_foreign_key('fk_fieldtypedevices_typedevices_id_device_type', 'fieldtypedevices', 'typedevices', ['device_type'], ['id'], ondelete='CASCADE')
    op.drop_column('fieldtypedevices', 'device')
    op.add_column('typedevices', sa.Column('device', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typedevices', 'device')
    op.add_column('fieldtypedevices', sa.Column('device', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint('fk_fieldtypedevices_typedevices_id_device_type', 'fieldtypedevices', type_='foreignkey')
    op.create_foreign_key('fk_fieldtypedevices_typedevices_id_device', 'fieldtypedevices', 'typedevices', ['device'], ['id'], ondelete='CASCADE')
    op.drop_column('fieldtypedevices', 'device_type')
    # ### end Alembic commands ###
