"""device type get

Revision ID: 5e67221cff42
Revises: 44256745298a
Create Date: 2024-11-11 20:53:35.767185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e67221cff42'
down_revision: Union[str, None] = '44256745298a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type_get_data', sa.String(length=200), nullable=True))
    op.add_column('devices', sa.Column('status', sa.String(length=200), nullable=True))
    op.drop_column('devices', 'device_polling')
    op.drop_column('devices', 'device_cyclic_polling')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_cyclic_polling', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_polling', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'type_get_data')
    # ### end Alembic commands ###
