"""story

Revision ID: 62bbf5f3863d
Revises: 730bf234ba69
Create Date: 2025-04-18 16:15:53.703715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bbf5f3863d'
down_revision: Union[str, None] = '730bf234ba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('status_device', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('values', 'status_device')
    # ### end Alembic commands ###
