"""story3

Revision ID: 65fad6c9847c
Revises: cf2579c1b12f
Create Date: 2025-05-29 19:28:03.304774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fad6c9847c'
down_revision: Union[str, None] = 'cf2579c1b12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typedevices', sa.Column('main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typedevices', 'main')
    # ### end Alembic commands ###
