"""user

Revision ID: 6ed69520ead1
Revises: 19c904febcce
Create Date: 2022-09-20 19:48:27.851136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed69520ead1'
down_revision = '19c904febcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicehistorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceName', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('datatime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('access', sa.Text(), nullable=False),
    sa.Column('refresh', sa.Text(), nullable=False),
    sa.Column('access_oauth', sa.Text(), nullable=True),
    sa.Column('refresh_oauth', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('oauth_host', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access', 'refresh', name='uc_sessions_access_refresh')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uc_users_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('devicehistorys')
    # ### end Alembic commands ###
