"""virtual field

Revision ID: 72fa494fd004
Revises: e38efe912cdf
Create Date: 2023-09-29 20:43:28.412154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fa494fd004'
down_revision = 'e38efe912cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('virtual_field', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'virtual_field')
    # ### end Alembic commands ###
