"""related_name

Revision ID: 86f8b56ceecb
Revises: fca8d24e0bd6
Create Date: 2023-09-29 20:55:38.968784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f8b56ceecb'
down_revision = 'fca8d24e0bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
