"""icon navigete

Revision ID: 905ad0e723ff
Revises: 701a49772960
Create Date: 2023-06-03 21:21:41.207774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ad0e723ff'
down_revision = '701a49772960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuelements', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menuelements', 'icon')
    # ### end Alembic commands ###
