"""Описание изменений

Revision ID: 92cccb10c3c7
Revises: fe104e1a74cb
Create Date: 2025-02-10 11:24:43.838475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92cccb10c3c7'
down_revision: Union[str, None] = 'fe104e1a74cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionelseitems', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('actionelseitems', sa.Column('field', sa.String(length=200), nullable=False))
    op.alter_column('actionelseitems', 'data',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.drop_column('actionelseitems', 'set')
    op.add_column('actionitems', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('actionitems', sa.Column('field', sa.String(length=200), nullable=False))
    op.alter_column('actionitems', 'data',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.drop_column('actionitems', 'set')
    op.add_column('conditionitems', sa.Column('arg2_service', sa.String(length=200), nullable=False))
    op.drop_column('conditionitems', 'arg2_ervice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditionitems', sa.Column('arg2_ervice', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('conditionitems', 'arg2_service')
    op.add_column('actionitems', sa.Column('set', mysql.VARCHAR(length=400), nullable=False))
    op.alter_column('actionitems', 'data',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('actionitems', 'field')
    op.drop_column('actionitems', 'index')
    op.add_column('actionelseitems', sa.Column('set', mysql.VARCHAR(length=400), nullable=False))
    op.alter_column('actionelseitems', 'data',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('actionelseitems', 'field')
    op.drop_column('actionelseitems', 'index')
    # ### end Alembic commands ###
