"""entity device

Revision ID: 92d4d7d01382
Revises: 6a25ef53cee1
Create Date: 2024-01-02 19:53:14.121615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d4d7d01382'
down_revision = '6a25ef53cee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_fields', sa.Column('entity', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_fields', 'entity')
    # ### end Alembic commands ###
