"""value

Revision ID: 964e0ff15815
Revises: 1cec96a59c6f
Create Date: 2023-09-30 21:41:06.632962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '964e0ff15815'
down_revision = '1cec96a59c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('value', sa.String(length=500), nullable=False))
    op.drop_column('values', 'deviceName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('deviceName', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('values', 'value')
    # ### end Alembic commands ###
