"""device field tag

Revision ID: ad78a1a23f7e
Revises: b5d3e75dae98
Create Date: 2025-04-25 20:18:31.437995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad78a1a23f7e'
down_revision: Union[str, None] = 'b5d3e75dae98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicefields', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('devicefields', sa.Column('tag', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devicefields', 'tag')
    op.drop_column('devicefields', 'category')
    # ### end Alembic commands ###
