"""room3

Revision ID: b1dc329e6c03
Revises: f07f548519d7
Create Date: 2025-06-24 22:18:26.819384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1dc329e6c03'
down_revision: Union[str, None] = 'f07f548519d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_devices', sa.Column('device', sa.String(length=200), nullable=True))
    op.add_column('room_devices', sa.Column('room', sa.String(length=200), nullable=True))
    op.drop_constraint('fk_room_devices_devices_system_name_devices', 'room_devices', type_='foreignkey')
    op.drop_constraint('fk_room_devices_rooms_name_rooms', 'room_devices', type_='foreignkey')
    op.create_foreign_key('fk_room_devices_devices_system_name_device', 'room_devices', 'devices', ['device'], ['system_name'], ondelete='CASCADE')
    op.create_foreign_key('fk_room_devices_rooms_name_room', 'room_devices', 'rooms', ['room'], ['name'], ondelete='CASCADE')
    op.drop_column('room_devices', 'devices')
    op.drop_column('room_devices', 'rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_devices', sa.Column('rooms', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('room_devices', sa.Column('devices', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint('fk_room_devices_rooms_name_room', 'room_devices', type_='foreignkey')
    op.drop_constraint('fk_room_devices_devices_system_name_device', 'room_devices', type_='foreignkey')
    op.create_foreign_key('fk_room_devices_rooms_name_rooms', 'room_devices', 'rooms', ['rooms'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('fk_room_devices_devices_system_name_devices', 'room_devices', 'devices', ['devices'], ['system_name'], ondelete='CASCADE')
    op.drop_column('room_devices', 'room')
    op.drop_column('room_devices', 'device')
    # ### end Alembic commands ###
