"""auhtomation trigger

Revision ID: b5d3e75dae98
Revises: 1923b7381e2f
Create Date: 2025-04-20 15:00:06.693882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d3e75dae98'
down_revision: Union[str, None] = '1923b7381e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targetitems', sa.Column('option', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targetitems', 'option')
    # ### end Alembic commands ###
