"""virtual false

Revision ID: becffab66bd9
Revises: 24b791ff3399
Create Date: 2023-12-24 12:24:06.475952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becffab66bd9'
down_revision = '24b791ff3399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
