"""get_value_type

Revision ID: cf2579c1b12f
Revises: 5db2f9acac78
Create Date: 2025-05-28 13:10:16.705287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2579c1b12f'
down_revision: Union[str, None] = '5db2f9acac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicefields', sa.Column('type_get_value', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devicefields', 'type_get_value')
    # ### end Alembic commands ###
