"""role

Revision ID: d9d7d5f9d7fa
Revises: d91105e25b21
Create Date: 2022-10-07 23:50:40.719492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d7d5f9d7fa'
down_revision = 'd91105e25b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
