"""automation

Revision ID: db38d01fe3dc
Revises: dc7076050fc2
Create Date: 2025-08-18 20:16:12.222281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db38d01fe3dc'
down_revision: Union[str, None] = 'dc7076050fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionitems', sa.Column('action', sa.String(length=200), nullable=False))
    op.drop_column('actionitems', 'field')
    op.drop_column('actionitems', 'object')
    op.add_column('conditionitems', sa.Column('arg1', sa.String(length=500), nullable=True))
    op.add_column('conditionitems', sa.Column('arg2', sa.String(length=500), nullable=True))
    op.drop_column('conditionitems', 'arg1_object')
    op.drop_column('conditionitems', 'arg2_object')
    op.drop_column('conditionitems', 'arg1_data')
    op.drop_column('conditionitems', 'arg2_data')
    op.add_column('targetitems', sa.Column('trigger', sa.String(length=400), nullable=False))
    op.drop_column('targetitems', 'data')
    op.drop_column('targetitems', 'object')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targetitems', sa.Column('object', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('targetitems', sa.Column('data', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('targetitems', 'trigger')
    op.add_column('conditionitems', sa.Column('arg2_data', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('conditionitems', sa.Column('arg1_data', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('conditionitems', sa.Column('arg2_object', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('conditionitems', sa.Column('arg1_object', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('conditionitems', 'arg2')
    op.drop_column('conditionitems', 'arg1')
    op.add_column('actionitems', sa.Column('object', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('actionitems', sa.Column('field', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('actionitems', 'action')
    # ### end Alembic commands ###
