"""room

Revision ID: dc7076050fc2
Revises: eaf9aa979e7b
Create Date: 2025-06-27 12:19:13.506990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7076050fc2'
down_revision: Union[str, None] = 'eaf9aa979e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('position_in_room', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'position_in_room')
    # ### end Alembic commands ###
