"""autogenerate

Revision ID: df58d38caf3c
Revises: 5e67221cff42
Create Date: 2025-02-09 19:06:07.406334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df58d38caf3c'
down_revision: Union[str, None] = '5e67221cff42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('actionelseitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.Column('set', sa.String(length=400), nullable=False),
    sa.Column('type_set', sa.String(length=10), nullable=True),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_actionelseitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actionitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.Column('set', sa.String(length=400), nullable=False),
    sa.Column('type_set', sa.String(length=10), nullable=True),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_actionitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditionitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.Column('arg1_service', sa.String(length=200), nullable=False),
    sa.Column('arg1_object', sa.String(length=200), nullable=True),
    sa.Column('arg1_data', sa.String(length=200), nullable=False),
    sa.Column('arg2_ervice', sa.String(length=200), nullable=False),
    sa.Column('arg2_object', sa.String(length=200), nullable=True),
    sa.Column('arg2_data', sa.String(length=200), nullable=False),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_conditionitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targetitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('object', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.Column('automation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['automation'], ['automations.name'], name='fk_targetitems_automations_name_automation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targetitems')
    op.drop_table('conditionitems')
    op.drop_table('actionitems')
    op.drop_table('actionelseitems')
    op.drop_table('automations')
    # ### end Alembic commands ###
