"""room

Revision ID: eaf9aa979e7b
Revises: b1dc329e6c03
Create Date: 2025-06-27 12:13:35.742994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaf9aa979e7b'
down_revision: Union[str, None] = 'b1dc329e6c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_devices')
    op.add_column('devices', sa.Column('room', sa.String(length=200), nullable=True))
    op.create_foreign_key('fk_devices_rooms_name_room', 'devices', 'rooms', ['room'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devices_rooms_name_room', 'devices', type_='foreignkey')
    op.drop_column('devices', 'room')
    op.create_table('room_devices',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('poz', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('device', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('room', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['devices.system_name'], name='fk_room_devices_devices_system_name_device', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room'], ['rooms.name'], name='fk_room_devices_rooms_name_room', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
