"""room2

Revision ID: f07f548519d7
Revises: 44d0c61108bb
Create Date: 2025-06-24 22:14:28.263794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07f548519d7'
down_revision: Union[str, None] = '44d0c61108bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_devices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('devices', sa.String(length=200), nullable=True),
    sa.Column('rooms', sa.String(length=200), nullable=True),
    sa.Column('poz', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['devices'], ['devices.system_name'], name='fk_room_devices_devices_system_name_devices', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rooms'], ['rooms.name'], name='fk_room_devices_rooms_name_rooms', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_devices')
    # ### end Alembic commands ###
