"""session

Revision ID: c4f0950e2677
Revises: d15290b186fd
Create Date: 2025-08-02 10:32:07.267342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4f0950e2677'
down_revision: Union[str, None] = 'd15290b186fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uc_sessionmoduleservices_token', table_name='sessionmoduleservices')
    op.drop_table('sessionmoduleservices')
    op.add_column('sessions', sa.Column('type', sa.String(length=20), nullable=False))
    op.alter_column('sessions', 'access',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'refresh',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'refresh',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('sessions', 'access',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('sessions', 'type')
    op.create_table('sessionmoduleservices',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('service', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('token', mysql.TEXT(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('host', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_sessionmoduleservices_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uc_sessionmoduleservices_token', 'sessionmoduleservices', ['token'], unique=True)
    # ### end Alembic commands ###
