"""services

Revision ID: d15290b186fd
Revises: 48e0751b5ec5
Create Date: 2025-08-01 12:08:34.310843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15290b186fd'
down_revision: Union[str, None] = '48e0751b5ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionmoduleservices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_sessionmoduleservices_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uc_sessionmoduleservices_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionmoduleservices')
    # ### end Alembic commands ###
