homeassistant:
  enabled: false
permit_join: false
frontend:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: root
  password: root
serial:
  port: tcp://192.168.1.50:6638
  adapter: zstack
  baudrate: 115200
  disable_led: false
advanced:
  transmit_power: 20
  network_key:
    - 198
    - 236
    - 39
    - 42
    - 155
    - 33
    - 8
    - 70
    - 23
    - 87
    - 148
    - 162
    - 236
    - 246
    - 198
    - 207
  pan_id: 41540
  ext_pan_id:
    - 17
    - 86
    - 89
    - 212
    - 66
    - 205
    - 226
    - 213
version: 4
devices:
  '0x04cf8cdf3c7b5bf0':
    friendly_name: '0x04cf8cdf3c7b5bf0'
