homeassistant: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: admin
  password: admin
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0005884fb7':
    friendly_name: temp1
  '0x00158d0005427bff':
    friendly_name: motionSensor
  '0x00158d0002a1d0ac':
    friendly_name: coub
  '0x04cf8cdf3c7b5bf0':
    friendly_name: luxMetor
  '0x00158d000548e74b':
    friendly_name: openDoorSensor
  '0x00158d00075db2f6':
    friendly_name: switch
