homeassistant: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto:1883'
  user: admin
  password: admin
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0005884fb7':
    friendly_name: temp1
  '0x00158d0005427bff':
    friendly_name: '0x00158d0005427bff'
  '0x00158d0002a1d0ac':
    friendly_name: coub
  '0x04cf8cdf3c7b5bf0':
    friendly_name: luxMetor
