version: "3.3"

services:
  mqtt_page:
    container_name: mqtt_page
    build:
      context: ./mqtt-page
      dockerfile: Dockerfile
      args:
        CONTAINER_NAME: mqtt_page
        PORT: 3000
        NEXT_BASE_PATH: "/modules/mqtt_page"
    command: sh -c "cp -r /app/config_local/* /app/config && npm run start"
    restart: always
    environment:
      RMQ_HOST: ${RABITMQ_HOST}
      RMQ_PORT: ${RABITMQ_PORT}
      EXCHANGE_SERVICE_DATA: ${EXCHANGE_SERVICE_DATA}
    labels:
      - "traefik.enable=true"
      # http (без TLS)
      - "traefik.http.routers.mqtt_http.rule=PathPrefix(`/modules/mqtt_page`)"
      - "traefik.http.routers.mqtt_http.entrypoints=web"
      - "traefik.http.routers.mqtt_http.service=mqtt"
      # https (с TLS)
      - "traefik.http.routers.mqtt_https.rule=PathPrefix(`/modules/mqtt_page`)"
      - "traefik.http.routers.mqtt_https.entrypoints=websecure"
      - "traefik.http.routers.mqtt_https.tls=true"
      - "traefik.http.routers.mqtt_https.service=mqtt"
      # общий сервис
      - "traefik.http.services.mqtt.loadbalancer.server.port=3000"
      - "traefik.http.routers.mqtt.middlewares=moduleauth@docker,module-mqtt_page-strip"
      - "traefik.http.middlewares.module-mqtt_page-strip.stripprefixregex.regex=^/modules/mqtt_page"
    volumes:
      - ./Configurate/mqtt_page:/app/config
    depends_on:
      rabbitmq:
        condition: service_healthy