services:
  traefik:
    image: traefik:v3.0
    restart: always
    networks: 
      - local_auth_network
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --log.level=INFO
      - --api.insecure=true   # включить Dashboard без авторизации (только для локалки)
      - --entrypoints.websecure.address=:443
    ports:
      - "1337:80"
      - "1338:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./certs:/certs:ro

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks: 
      - local_auth_network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 15s
      timeout: 15s
      retries: 3
    ports:
      - ${RABITMQ_OUT_PORT}:15672
      - ${RABITMQ_PORT}:${RABITMQ_PORT}

networks:
  local_auth_network:
    name: ${NETWORK_NAME}
    external: true