- address: test
  name: testdev
  systemName: testdev
  token: null
  type: light
  typeConnect: mqtt
  valueType: json
  values:
  - address: field0
    control: true
    high: '100'
    icon: fas fa-cog
    low: '0'
    name: field0
    type: binary
    unit: ''
    value: 1
    values: ''
  - address: field1
    control: true
    high: '100'
    icon: fas fa-bolt
    low: '0'
    name: field1
    type: text
    unit: ''
    value: cvbd
    values: ''
- address: 192.168.0.7
  name: "\u043B\u0430\u043C\u043F\u0430 \u0432 \u0441\u043F\u0430\u043B\u044C\u043D\
    \u0435"
  systemName: lamp1
  token: null
  type: light
  typeConnect: yeelight
  valueType: json
  values:
  - address: null
    control: true
    high: 1
    icon: fas fa-power-off
    low: 0
    name: state
    type: binary
    unit: null
    value: '0'
    values: null
  - address: null
    control: true
    high: 100
    icon: far fa-sun
    low: 0
    name: brightness
    type: number
    unit: null
    value: '100'
    values: null
  - address: null
    control: true
    high: '1'
    icon: fas fa-moon
    low: 0
    name: night_light
    type: binary
    unit: null
    value: '0'
    values: null
  - address: null
    control: true
    high: 6500
    icon: fas fa-adjust
    low: 2700
    name: temp
    type: number
    unit: null
    value: '2700'
    values: null
- address: zigbee2mqtt/coub
  name: "\u043A\u0443\u0431"
  systemName: magicCub
  token: null
  type: sensor
  typeConnect: zigbee
  valueType: json
  values:
  - address: battery
    control: false
    high: 100
    icon: ''
    low: 0
    name: battery
    type: number
    unit: '%'
    value: 100
    values: ''
  - address: voltage
    control: false
    high: 1000000
    icon: ''
    low: 0
    name: voltage
    type: number
    unit: mV
    value: 3005
    values: ''
  - address: action_angle
    control: false
    high: 360
    icon: ''
    low: -360
    name: action_angle
    type: number
    unit: ''
    value: -492.7
    values: ''
  - address: action_from_side
    control: false
    high: 6
    icon: ''
    low: 0
    name: action_from_side
    type: number
    unit: ''
    value: 3
    values: ''
  - address: action_side
    control: false
    high: 6
    icon: ''
    low: 0
    name: action_side
    type: number
    unit: ''
    value: 1
    values: ''
  - address: action_to_side
    control: false
    high: 6
    icon: ''
    low: 0
    name: action_to_side
    type: number
    unit: ''
    value: 1
    values: ''
  - address: action
    control: false
    high: 1000000
    icon: ''
    low: 0
    name: action
    type: enum
    unit: ''
    value: wakeup
    values: shake, wakeup, fall, tap, slide, flip180, flip90, rotate_left, rotate_right
  - address: linkquality
    control: false
    high: 255
    icon: ''
    low: 0
    name: linkquality
    type: number
    unit: lqi
    value: 173
    values: ''
- address: zigbee2mqtt/switch
  name: switch1
  systemName: switch1
  token: null
  type: switch
  typeConnect: zigbee
  valueType: json
  values:
  - address: state_left
    control: left
    high: 'ON'
    icon: fas fa-power-off
    low: 'OFF'
    name: left
    type: binary
    unit: ''
    value: '0'
    values: ''
  - address: state_right
    control: right
    high: 'ON'
    icon: fas fa-power-off
    low: 'OFF'
    name: right
    type: binary
    unit: ''
    value: '0'
    values: ''
  - address: power
    control: false
    high: 1000000
    icon: ''
    low: 0
    name: power
    type: number
    unit: W
    value: 0
    values: ''
  - address: action
    control: false
    high: 1000000
    icon: ''
    low: 0
    name: action
    type: enum
    unit: ''
    value: single_right
    values: hold_left, single_left, double_left, release_left, hold_right, single_right,
      double_right, release_right, hold_both, single_both, double_both, release_both
  - address: operation_mode_left
    control: left
    high: 1000000
    icon: ''
    low: 0
    name: operation_mode_left
    type: enum
    unit: ''
    value: decoupled
    values: control_left_relay, decoupled
  - address: operation_mode_right
    control: right
    high: 1000000
    icon: ''
    low: 0
    name: operation_mode_right
    type: enum
    unit: ''
    value: control_right_relay
    values: control_right_relay, decoupled
  - address: linkquality
    control: false
    high: 255
    icon: ''
    low: 0
    name: linkquality
    type: number
    unit: lqi
    value: 134
    values: ''
- address: zigbee2mqtt/bridge
  name: zigbee2mqtt
  systemName: zigbee2mqtt
  token: null
  type: sensor
  typeConnect: mqtt
  valueType: value
  values:
  - address: state
    control: false
    high: online
    icon: fas fa-broadcast-tower
    low: offline
    name: state
    type: binary
    unit: ''
    value: '0'
    values: ''
