- title: "light"
  ditailType: "light"
  interface:
  - name: "yeelight"
  - name: "mqtt"
  - name: "zigbee"
- title: "switchs"
  ditailType: "switch"
  interface:
  - name: "mqtt"
  - name: "zigbee"
- title: "wireless switchs"
  ditailType: "sensor"
  interface:
  - name: "mqtt"
  - name: "zigbee"
- title: "relay"
  ditailType: "switch"
  interface:
  - name: "mqtt"
  - name: "zigbee"
- title: "socket"
  ditailType: "switch"
  interface:
  - name: "mqtt"
  - name: "zigbee"
- title: "sensor"
  ditailType: "sensor"
  interface:
  - name: "mqtt"
  - name: "zigbee"
